(defun remove-quotes (string)
  (subseq string 1 (1- (length string))))

(defun read-word-list (filename)
  (with-open-file (stream (probe-file filename))
                  (split-string (read-line stream nil) #\,)))

(defun split-string (string delimeter)
  (let ((word-list nil))
    (do* ((pos 0 pos)
          (next-pos (position delimeter string)
                    (position delimeter string :start pos)))
        ((eq next-pos nil) (push (subseq string pos) word-list))
      (push (subseq string pos next-pos) word-list)
      (setf pos (1+ next-pos)))
    (reverse word-list)))
