;;;;
;;;; Project Euler - Problem 2
;;;;
;;;; Each new term in the Fibonacci sequence is generated by adding the
;;;; previous two terms. By starting with 1 and 2, the first 10 terms will
;;;; be:
;;;;
;;;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;;;
;;;; Find the sum of all the even-valued terms in the sequence which do
;;;; not exceed four million.
;;;;

(load "fibonacci.lisp")

(defun euler002 ()
  (fibonacci-init 100)
  (let ((lastfib 0)
        (sum 0))
    (do ((i 2 (1+ i)))
        ((> lastfib 4000000) sum)
      (setf lastfib (fibonacci i))
      (if (evenp lastfib)
          (setf sum (+ sum lastfib))))))
